#!/usr/bin/env python3
import sys
import os
import argparse
import pickle
from pathlib import Path

# Add the fuzzing directory to path
sys.path.append(str(Path(__file__).resolve().parent.parent))

try:
    from conductor.trace_analyzer import TraceAnalyzer
except ImportError:
    print("[-] Error: Could not import TraceAnalyzer. Make sure PYTHONPATH is set.")
    sys.exit(1)

def extract_network_payload(trace_path):
    """
    Extract network payload from a trace file using TraceAnalyzer
    """
    print(f"[*] Analyzing trace: {trace_path}")
    
    # Try to load cached analyzer if available
    pkl_path = Path(trace_path).with_suffix(Path(trace_path).suffix + ".analyzer.pkl")
    if pkl_path.exists():
        print(f"[*] Loading cached analysis from {pkl_path}")
        try:
            with open(pkl_path, 'rb') as f:
                loaded_data = pickle.load(f)
                if isinstance(loaded_data, dict) and 'syscalls' in loaded_data:
                    syscalls = loaded_data['syscalls']
                else:
                    syscalls = loaded_data
        except Exception as e:
            print(f"[!] Warning: Failed to load cache: {e}. Re-analyzing...")
            analyzer = TraceAnalyzer(trace_path)
            syscalls = analyzer.syscalls
    else:
        print("[*] Performing fresh analysis...")
        analyzer = TraceAnalyzer(trace_path)
        syscalls = analyzer.syscalls

    payload = b""
    # Common input-related syscalls across architectures
    # NR 3: read, NR 145: readv, NR 291: recv, NR 292: recvfrom etc on ARM
    # NR 3: read, NR 45: recvfrom on MIPS
    
    input_categories = ['input_io', 'network', 'unknown']
    
    for s in syscalls:
        # Check if the syscall has aux_entries (raw data captured during execution)
        if hasattr(s, 'aux_entries') and s.aux_entries:
            # Most network read syscalls store their buffer in aux_entries
            for entry in s.aux_entries:
                if len(entry) >= 3:
                    data = entry[2]
                    if isinstance(data, bytes) and len(data) > 0:
                        payload += data
        elif hasattr(s, 'arg_data') and s.arg_data:
             # Fallback for some analyzers that store data in arg_data
             for arg_idx, data in s.arg_data.items():
                 if isinstance(data, bytes) and len(data) > 0:
                     payload += data

    return payload

def generate_poc(payload, out_path, host, port):
    """
    Generate a Python PoC script
    """
    template = f"""#!/usr/bin/env python3
import socket
import sys

# Generated by RR-Fuzz trace_to_poc.py
# Target: {host}:{port}
# Payload Length: {len(payload)}

PAYLOAD = {repr(payload)}

def exploit(host, port):
    print(f"[*] Sending payload ({{len(PAYLOAD)}} bytes) to {{host}}:{{port}}...")
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(10)
        s.connect((host, port))
        s.sendall(PAYLOAD)
        
        # Keep connection open for a bit to ensure the crash is triggered
        try:
            response = s.recv(4096)
            print("[+] Received response (first 64 bytes):")
            print(response[:64])
        except socket.timeout:
            print("[*] No response (Socket Timeout) - Server might have crashed!")
            
        s.close()
        print("[+] Exploit sent successfully.")
    except Exception as e:
        print(f"[-] Error: {{e}}")

if __name__ == "__main__":
    target_host = "{host}"
    target_port = {port}
    
    if len(sys.argv) > 1:
        target_host = sys.argv[1]
    if len(sys.argv) > 2:
        target_port = int(sys.argv[2])
        
    exploit(target_host, target_port)
"""
    
    with open(out_path, 'w') as f:
        f.write(template)
    
    # Make executable
    os.chmod(out_path, 0o755)
    print(f"[+] PoC generated: {out_path}")

def main():
    parser = argparse.ArgumentParser(description="RR-Fuzz Trace to PoC Toolkit")
    parser.add_argument("trace", help="Path to the crash trace file (.bin)")
    parser.add_argument("-o", "--output", help="Output filename for PoC", default="poc_generated.py")
    parser.add_argument("--host", help="Target host for PoC", default="127.0.0.1")
    parser.add_argument("-p", "--port", type=int, help="Target port for PoC", default=80)
    
    args = parser.parse_args()
    
    if not os.path.exists(args.trace):
        print(f"[-] Error: Trace file '{args.trace}' not found.")
        sys.exit(1)
        
    payload = extract_network_payload(args.trace)
    
    if not payload:
        print("[!] Warning: No network payload bytes extracted from trace.")
        print("[*] This trace might be a local file operation or internal logic crash.")
        # We'll still generate it but with empty payload
    else:
        print(f"[+] Successfully extracted {len(payload)} bytes of payload.")

    generate_poc(payload, args.output, args.host, args.port)

if __name__ == "__main__":
    main()
