#!/usr/bin/env python3
import json
import os
import stat

# Configuration
REPORT_FILE = "/home/webfuzz/Documents/qemu/linux-user/rr_fuzzing/mass_onboard_report.json"
OUTPUT_DIR = "/home/webfuzz/Documents/qemu/linux-user/rr_fuzzing/campaign_supplemental"
QEMU_BUILD_ROOT = "/home/webfuzz/Documents/qemu/build"

# Template for the fussing wrapper script
SCRIPT_TEMPLATE = """#!/bin/bash
# High-Performance Fuzzing Wrapper for {name}
# Auto-generated by generate_supplemental_campaign.py

# 1. Environment Setup
export QEMU_LD_PREFIX="{rootfs}"
export RR_SAFE_IPC_FD_START=200
export RR_MODE=record
export RR_TRACE_FILE="{trace_file}"
export LD_LIBRARY_PATH="{lib_path}"

# 2. Cleanup
rm -f "$RR_TRACE_FILE"

# 3. Execution
echo "[*] Starting Fuzzing for {name}..."
echo "    Target: {binary}"
echo "    Arch: {arch}"

# Loop to restart on crash (but we want to catch the crash!)
while true; do
  {qemu_cmd} \\
    -plugin ./lib/libqemufuzz.so,config=./config/fuzz_config.yml \\
    {conf_flag} {conf_path} \\
    {binary} {conf_flag_run} > "/dev/null" 2>&1
    
  EXIT_CODE=$?
  echo "    Exited with $EXIT_CODE"
  
  if [ $EXIT_CODE -eq 139 ] || [ $EXIT_CODE -eq -11 ]; then
      echo "CRASH DETECTED!"
      # Save the crash log/trace immediately
      cp "$RR_TRACE_FILE" "./crashes/crash_$(date +%s).log"
  fi
  
  sleep 1
done
"""

def get_config_flag(binary_name):
    if "httpd" in binary_name: return "-f" # standard for many
    if "lighttpd" in binary_name: return "-f"
    if "boa" in binary_name: return "-c"
    if "nginx" in binary_name: return "-c"
    return ""

def find_config(rootfs, binary_name):
    # Heuristic to find a config file
    # for httpd, look for httpd.conf
    # for boa, look for boa.conf
    # for lighttpd, look for lighttpd.conf
    
    base = binary_name.replace("mini_", "").replace("u", "")
    conf_name = f"{base}.conf"
    
    # search
    import subprocess
    cmd = f"find {rootfs} -name {conf_name} | head -n 1"
    path = subprocess.getoutput(cmd).strip()
    return path

def generate_campaign():
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    with open(REPORT_FILE, "r") as f:
        targets = json.load(f)

    # Filter for NEW targets only (heuristically, by name or path)
    # Or just simpler: any target that is NOT "Tenda", "Netis", "Totolink", "Asus", "Netgear"
    # Actually, user wants "more" targets. Let's include: Trendnet, TP-Link, D-Link, MikroTik
    # And maybe re-fuzz the others if we have capacity.
    # Let's prioritize the new ones.
    
    launch_script = []
    launch_script.append("#!/bin/bash")
    launch_script.append("echo 'Starting Supplemental Fuzzing Campaign...'")
    
    count = 0
    for t in targets:
        name = t['name']
        
        # Priority Filter
        is_priority = False
        if "Trendnet" in t['rootfs'] or "TEW" in name: is_priority = True
        if "TP-Link" in t['rootfs'] or "AXE75" in name: is_priority = True
        if "DLink" in t['rootfs'] or "DIR" in name: is_priority = True
        if "MikroTik" in t['rootfs']: is_priority = True
        
        if not is_priority:
            continue
            
        print(f"[*] Generating campaign for {name}...")
        
        # Paths
        rootfs = t['rootfs']
        binary_cmd = f"find {t['rootfs']} -name {t['web_server_binary']} -type f | head -n 1"
        import subprocess
        bin_full = subprocess.getoutput(binary_cmd).strip()
        
        if not bin_full:
            print(f"  [!] Skipped: Binary {t['web_server_binary']} not found in {t['rootfs']}")
            continue

        arch = t['arch']
        qemu_bin = os.path.join(QEMU_BUILD_ROOT, f"qemu-{arch}")
        
        # Lib Path
        lib_paths = [
            os.path.join(rootfs, "lib"),
            os.path.join(rootfs, "usr", "lib")
        ]
        lib_path_str = ":".join(lib_paths)
        
        # Trace file
        trace_file = f"/tmp/rr_trace_{name}.txt"
        
        # Config finding
        conf_path = find_config(rootfs, t['web_server_binary'])
        conf_flag = ""
        conf_flag_run = ""
        final_conf_path = ""
        
        if conf_path:
            conf_flag = get_config_flag(t['web_server_binary'])
            final_conf_path = conf_path
            # Boa hack
            if "boa" in t['web_server_binary']:
                final_conf_path = os.path.dirname(conf_path)
            
            conf_flag_run = f"{conf_flag} {final_conf_path}"

        # Script Content
        script_content = SCRIPT_TEMPLATE.format(
            name=name,
            rootfs=rootfs,
            trace_file=trace_file,
            lib_path=lib_path_str,
            qemu_cmd=qemu_bin,
            binary=bin_full,
            conf_flag=conf_flag, # This seems redundant in template? No, I put it effectively in conf_flag_run
            conf_path=final_conf_path, # Redundant
            arch=arch,
            conf_flag_run=conf_flag_run
        )
        
        # Fix the template redundancy: I used conf_flag_run in the template call
        # but the template has {conf_flag} {conf_path} AND {conf_flag_run}
        # Let's fix template usage dynamically
        
        # Actually, let's just write the simpler version
        final_script = f"""#!/bin/bash
export QEMU_LD_PREFIX="{rootfs}"
export RR_SAFE_IPC_FD_START=200
export RR_MODE=record
export RR_TRACE_FILE="{trace_file}"
export LD_LIBRARY_PATH="{lib_path_str}"

rm -f "{trace_file}"

echo "[*] Launching {name} ({arch})"
while true; do
  {qemu_bin} \\
    -plugin ./lib/libqemufuzz.so,config=./config/fuzz_config.yml \\
    {bin_full} {conf_flag_run} > /dev/null 2>&1
  
  RET=$?
  if [ $RET -eq 139 ] || [ $RET -eq -11 ]; then
      echo "CRASH: {name}"
      cp "{trace_file}" "./crashes/crash_{name}_$(date +%s).log"
  fi
  sleep 1
done
"""
        
        script_name = f"run_fuzz_{name}.sh"
        script_path = os.path.join(OUTPUT_DIR, script_name)
        
        with open(script_path, "w") as f:
            f.write(final_script)
        
        st = os.stat(script_path)
        os.chmod(script_path, st.st_mode | stat.S_IEXEC)
        
        launch_script.append(f"nohup {script_path} > /dev/null 2>&1 &")
        count += 1

    launch_script.append("echo '[+] All supplemental targets launched!'")
    
    with open("launch_supplemental.sh", "w") as f:
        f.write("\n".join(launch_script))
    
    os.chmod("launch_supplemental.sh", 0o755)
    print(f"Generated campaign for {count} targets.")

if __name__ == "__main__":
    generate_campaign()
